INSERT INTO user_balances (user_id, balance, created_at, updated_at)
VALUES
    (1, 1000000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 500000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 100000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (user_id) DO NOTHING;
